# Generated by Django 4.0.6 on 2022-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_option_option2_remove_option_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option1',
        ),
        migrations.AddField(
            model_name='option',
            name='option',
            field=models.TextField(blank=True, help_text='Required', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_count',
            field=models.IntegerField(default=0),
        ),
    ]
