# Generated by Django 4.0.6 on 2022-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_option_option1_option_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(blank=True, help_text='Required', max_length=250, null=True),
        ),
    ]
