# Generated by Django 4.0.6 on 2022-07-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_option_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='questions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='option',
            name='option_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
