# Generated by Django 4.0.6 on 2022-07-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_questions_polls_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='slug',
            field=models.CharField(blank=True, help_text='Required', max_length=255, null=True),
        ),
    ]
