# Generated by Django 4.0.6 on 2022-07-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_polls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='polls.polls'),
        ),
    ]
